### ISSUE TITLE
List Index Out of Bound

### ISSUE THREAD

**Issue by ghyan-shah** [itsShnik/gre-preparation-tool#2]
For "How many words do you want to learn today?" and input being equal to 50, line 309 "**_interactiveLearner(lists[list_num], num_words)_**" has its index out of range.

**Comment by itsShnik** [comment]
Make sure that the list you're trying to learn from has that many words, you should be able to check that from menu. All the best.

**Comment by ghyan-shah** [comment]
Hey Nikhil, I checked that first. I was going through "900+ essential GRE words" which has 966 words. However, a learning batch of 50 words seems to go out of range. 

![listTotal](https://user-images.githubusercontent.com/73254426/179352807-ac07d2c0-15ff-4605-b830-198c15b87034.JPG)

**Comment by itsShnik** [comment]
You gotta fix that yourself, man! I don't maintain this :)

**Comment by ghyan-shah** [comment]
Already fixed that from my side. However, you might wanna change this from your repo "You may contact us by opening an issue on this repo. Please allow 2-3 days of time to address the issue"
